# Introduction à R

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-à-R" data-toc-modified-id="Introduction-à-R-1">Introduction à R</a></span><ul class="toc-item"><li><span><a href="#I.-Prise-en-main-du-logiciel" data-toc-modified-id="I.-Prise-en-main-du-logiciel-1.1">I. Prise en main du logiciel</a></span><ul class="toc-item"><li><span><a href="#I.A.-Quelques-astuces-avant-de-commencer" data-toc-modified-id="I.A.-Quelques-astuces-avant-de-commencer-1.1.1">I.A. Quelques astuces avant de commencer</a></span></li><li><span><a href="#I.B.-Premières-manipulations" data-toc-modified-id="I.B.-Premières-manipulations-1.1.2">I.B. Premières manipulations</a></span><ul class="toc-item"><li><span><a href="#I.B.1.-Faites-tourner-le-code-ci-dessus-puis-faites-un-appel-à-la-fonction-ls().-À-quoi-sert-cette-fonction?" data-toc-modified-id="I.B.1.-Faites-tourner-le-code-ci-dessus-puis-faites-un-appel-à-la-fonction-ls().-À-quoi-sert-cette-fonction?-1.1.2.1">I.B.1. Faites tourner le code ci-dessus puis faites un appel à la fonction ls(). À quoi sert cette fonction?</a></span></li><li><span><a href="#I.B.2.-Appliquez-la-fonction-mode()-à-chacun-de-ces-objets.-Décrivez-les-différents-types-d’objets-obtenus." data-toc-modified-id="I.B.2.-Appliquez-la-fonction-mode()-à-chacun-de-ces-objets.-Décrivez-les-différents-types-d’objets-obtenus.-1.1.2.2">I.B.2. Appliquez la fonction mode() à chacun de ces objets. Décrivez les différents types d’objets obtenus.</a></span></li><li><span><a href="#I.B.3.-Que-font-les-fonctions-is.numeric,-is.logical-et-is.character?-Testez-les-sur-ces-objets." data-toc-modified-id="I.B.3.-Que-font-les-fonctions-is.numeric,-is.logical-et-is.character?-Testez-les-sur-ces-objets.-1.1.2.3">I.B.3. Que font les fonctions is.numeric, is.logical et is.character? Testez-les sur ces objets.</a></span></li><li><span><a href="#I.B.4.-Même-question-avec-as.numeric,-as.logical-et-as.character.-Expliquez-les-résultats-de-as.numeric(c)-et-as.logical(a)." data-toc-modified-id="I.B.4.-Même-question-avec-as.numeric,-as.logical-et-as.character.-Expliquez-les-résultats-de-as.numeric(c)-et-as.logical(a).-1.1.2.4">I.B.4. Même question avec as.numeric, as.logical et as.character. Expliquez les résultats de as.numeric(c) et as.logical(a).</a></span></li><li><span><a href="#I.B.5.-Trouvez-une-fonction-permettant-de-supprimer-des-objets-en-mémoire.-Utilisez-là-pour-supprimer-a,-puis-pour-supprimer-b-et-c." data-toc-modified-id="I.B.5.-Trouvez-une-fonction-permettant-de-supprimer-des-objets-en-mémoire.-Utilisez-là-pour-supprimer-a,-puis-pour-supprimer-b-et-c.-1.1.2.5">I.B.5. Trouvez une fonction permettant de supprimer des objets en mémoire. Utilisez-là pour supprimer a, puis pour supprimer b et c.</a></span></li><li><span><a href="#I.B.6.-Aprés-avoir-créé-de-nouveau-ces-objets,-trouvez-une-manière-de-supprimer-l’ensemble-des-objets-en-mémoire-(sans-faire-référence-à-leurs-noms)." data-toc-modified-id="I.B.6.-Aprés-avoir-créé-de-nouveau-ces-objets,-trouvez-une-manière-de-supprimer-l’ensemble-des-objets-en-mémoire-(sans-faire-référence-à-leurs-noms).-1.1.2.6">I.B.6. Aprés avoir créé de nouveau ces objets, trouvez une manière de supprimer l’ensemble des objets en mémoire (sans faire référence à leurs noms).</a></span></li></ul></li><li><span><a href="#I.C.-Documentation-des-fonctions" data-toc-modified-id="I.C.-Documentation-des-fonctions-1.1.3">I.C. Documentation des fonctions</a></span><ul class="toc-item"><li><span><a href="#I.C.1.-Trouvez-une-manière-d’afficher-l’aide-de-la-fonction-is.numeric.-Essayez-d’identifier-les-grandes-parties-de-cette-documentation." data-toc-modified-id="I.C.1.-Trouvez-une-manière-d’afficher-l’aide-de-la-fonction-is.numeric.-Essayez-d’identifier-les-grandes-parties-de-cette-documentation.-1.1.3.1">I.C.1. Trouvez une manière d’afficher l’aide de la fonction is.numeric. Essayez d’identifier les grandes parties de cette documentation.</a></span></li><li><span><a href="#I.C.2.-Lancez-??is.numeric.-Qu’est-ce-qu’on-obtient?" data-toc-modified-id="I.C.2.-Lancez-??is.numeric.-Qu’est-ce-qu’on-obtient?-1.1.3.2">I.C.2. Lancez ??is.numeric. Qu’est-ce qu’on obtient?</a></span></li><li><span><a href="#I.C.3.-Trouvez-comment-afficher-le-code-d’une-fonction-R-dans-la-console." data-toc-modified-id="I.C.3.-Trouvez-comment-afficher-le-code-d’une-fonction-R-dans-la-console.-1.1.3.3">I.C.3. Trouvez comment afficher le code d’une fonction R dans la console.</a></span></li></ul></li></ul></li><li><span><a href="#II.-Manipulations-d’objets" data-toc-modified-id="II.-Manipulations-d’objets-1.2">II. Manipulations d’objets</a></span><ul class="toc-item"><li><span><a href="#II.A.-Création-de-vecteurs" data-toc-modified-id="II.A.-Création-de-vecteurs-1.2.1">II.A. Création de vecteurs</a></span><ul class="toc-item"><li><span><a href="#II.A.1.-Affichez-la-documentation-de-la-fonction-c()." data-toc-modified-id="II.A.1.-Affichez-la-documentation-de-la-fonction-c().-1.2.1.1">II.A.1. Affichez la documentation de la fonction c().</a></span></li><li><span><a href="#II.A.2.-Trouvez-une-fonction-permettant-de-vérifier-que-ce-vecteur-est-bien-numérique." data-toc-modified-id="II.A.2.-Trouvez-une-fonction-permettant-de-vérifier-que-ce-vecteur-est-bien-numérique.-1.2.1.2">II.A.2. Trouvez une fonction permettant de vérifier que ce vecteur est bien numérique.</a></span></li><li><span><a href="#II.A.3.-Trouvez-une-manière-d’afficher-la-longueur-de-ce-vecteur." data-toc-modified-id="II.A.3.-Trouvez-une-manière-d’afficher-la-longueur-de-ce-vecteur.-1.2.1.3">II.A.3. Trouvez une manière d’afficher la longueur de ce vecteur.</a></span></li><li><span><a href="#II.A.4.-Faites-tourner-str(my_vec).-Qu’obtient-on?" data-toc-modified-id="II.A.4.-Faites-tourner-str(my_vec).-Qu’obtient-on?-1.2.1.4">II.A.4. Faites tourner str(my_vec). Qu’obtient-on?</a></span></li><li><span><a href="#II.A.5.-Ajoutez-deux-valeurs-numériques-à-votre-vecteur-sans-le-créer-de-nouveau." data-toc-modified-id="II.A.5.-Ajoutez-deux-valeurs-numériques-à-votre-vecteur-sans-le-créer-de-nouveau.-1.2.1.5">II.A.5. Ajoutez deux valeurs numériques à votre vecteur sans le créer de nouveau.</a></span></li><li><span><a href="#II.A.6.-Refaire-les-étapes-ci-dessus-avec-cette-fois-my_vec_logi-composé-d’éléments-logiques-et-my_vec_charac-composé-d’éléments-caractères." data-toc-modified-id="II.A.6.-Refaire-les-étapes-ci-dessus-avec-cette-fois-my_vec_logi-composé-d’éléments-logiques-et-my_vec_charac-composé-d’éléments-caractères.-1.2.1.6">II.A.6. Refaire les étapes ci-dessus avec cette fois my_vec_logi composé d’éléments logiques et my_vec_charac composé d’éléments caractères.</a></span></li><li><span><a href="#II.A.7.-Concaténez-my_vec_num,-my_vec_logi-et-my_vec_charac.-Quel-type-de-vecteur-obtient-on?" data-toc-modified-id="II.A.7.-Concaténez-my_vec_num,-my_vec_logi-et-my_vec_charac.-Quel-type-de-vecteur-obtient-on?-1.2.1.7">II.A.7. Concaténez my_vec_num, my_vec_logi et my_vec_charac. Quel type de vecteur obtient-on?</a></span></li></ul></li><li><span><a href="#II.B.-Opérations-de-base-sur-les-vecteurs" data-toc-modified-id="II.B.-Opérations-de-base-sur-les-vecteurs-1.2.2">II.B. Opérations de base sur les vecteurs</a></span><ul class="toc-item"><li><span><a href="#II.B.1.-Trouvez-une-manière-de-créer-un-vecteur-répliquant-le-même-élément-n-fois." data-toc-modified-id="II.B.1.-Trouvez-une-manière-de-créer-un-vecteur-répliquant-le-même-élément-n-fois.-1.2.2.1">II.B.1. Trouvez une manière de créer un vecteur répliquant le même élément n fois.</a></span></li><li><span><a href="#II.B.2.-Créez-un-vecteur-c1-contenant-les-chiffres-allant-de-8-à-30-en-utilisant-deux-méthodes-différentes." data-toc-modified-id="II.B.2.-Créez-un-vecteur-c1-contenant-les-chiffres-allant-de-8-à-30-en-utilisant-deux-méthodes-différentes.-1.2.2.2">II.B.2. Créez un vecteur c1 contenant les chiffres allant de 8 à 30 en utilisant deux méthodes différentes.</a></span></li><li><span><a href="#II.B.3.-Trouvez-une-manière-d’afficher-le-1er-élément-de-c1,-puis-le-15e.-Vous-notez-une-différence-avec-Python?" data-toc-modified-id="II.B.3.-Trouvez-une-manière-d’afficher-le-1er-élément-de-c1,-puis-le-15e.-Vous-notez-une-différence-avec-Python?-1.2.2.3">II.B.3. Trouvez une manière d’afficher le 1er élément de c1, puis le 15e. Vous notez une différence avec Python?</a></span></li><li><span><a href="#II.B.4.-Créez-un-vecteur-c2-contenant-le-2nd,-le-5e-et-le-8e-élément-de-c1." data-toc-modified-id="II.B.4.-Créez-un-vecteur-c2-contenant-le-2nd,-le-5e-et-le-8e-élément-de-c1.-1.2.2.4">II.B.4. Créez un vecteur c2 contenant le 2nd, le 5e et le 8e élément de c1.</a></span></li><li><span><a href="#II.B.5.-Créez-un-vecteur-c3-contenant-tous-les-éléments-de-c2-sauf-le-2e." data-toc-modified-id="II.B.5.-Créez-un-vecteur-c3-contenant-tous-les-éléments-de-c2-sauf-le-2e.-1.2.2.5">II.B.5. Créez un vecteur c3 contenant tous les éléments de c2 sauf le 2e.</a></span></li><li><span><a href="#II.B.6.-Faites-tourner-names(c2)-<--c(&quot;pommes&quot;,&quot;poires&quot;,-&quot;prunes&quot;)-puis-affichez-c2-et-str(c2).-Que-s’est-il-passé?" data-toc-modified-id="II.B.6.-Faites-tourner-names(c2)-<--c(&quot;pommes&quot;,&quot;poires&quot;,-&quot;prunes&quot;)-puis-affichez-c2-et-str(c2).-Que-s’est-il-passé?-1.2.2.6">II.B.6. Faites tourner names(c2) &lt;- c("pommes","poires", "prunes") puis affichez c2 et str(c2). Que s’est-il passé?</a></span></li><li><span><a href="#II.B.7.-Essayez-d’utiliser-des-fonctions-de-statistiques-de-base-directement-sur-des-vecteurs-(somme,-moyenne,-min,-max).-Comment-s’appliquent-elles?" data-toc-modified-id="II.B.7.-Essayez-d’utiliser-des-fonctions-de-statistiques-de-base-directement-sur-des-vecteurs-(somme,-moyenne,-min,-max).-Comment-s’appliquent-elles?-1.2.2.7">II.B.7. Essayez d’utiliser des fonctions de statistiques de base directement sur des vecteurs (somme, moyenne, min, max). Comment s’appliquent-elles?</a></span></li></ul></li><li><span><a href="#II.C.-Expressions-logiques-et-conditions" data-toc-modified-id="II.C.-Expressions-logiques-et-conditions-1.2.3">II.C. Expressions logiques et conditions</a></span><ul class="toc-item"><li><span><a href="#II.C.1.-Faites-tourner-c1-<-16." data-toc-modified-id="II.C.1.-Faites-tourner-c1-<-16.-1.2.3.1">II.C.1. Faites tourner c1 &lt; 16.</a></span></li><li><span><a href="#II.C.2.-Sortez-le-vecteur-de-condition-“c1-est-égal-à-12-ou-à-28”." data-toc-modified-id="II.C.2.-Sortez-le-vecteur-de-condition-“c1-est-égal-à-12-ou-à-28”.-1.2.3.2">II.C.2. Sortez le vecteur de condition “c1 est égal à 12 ou à 28”.</a></span></li><li><span><a href="#II.C.3.-Créez-le-vecteur-de-condition-cond1-“c1-est-supérieur-à-16-et-inférieur-à-22”." data-toc-modified-id="II.C.3.-Créez-le-vecteur-de-condition-cond1-“c1-est-supérieur-à-16-et-inférieur-à-22”.-1.2.3.3">II.C.3. Créez le vecteur de condition cond1 “c1 est supérieur à 16 et inférieur à 22”.</a></span></li><li><span><a href="#II.C.4.-Faites-tourner-c1[cond1].-Qu’observez-vous?" data-toc-modified-id="II.C.4.-Faites-tourner-c1[cond1].-Qu’observez-vous?-1.2.3.4">II.C.4. Faites tourner c1[cond1]. Qu’observez vous?</a></span></li><li><span><a href="#II.C.5.-Utilisez-la-même-logique-pour-créer-un-vecteur-c4-contenant-les-valeurs-entre-8-et-12-et-entre-15-et-17-de-c1." data-toc-modified-id="II.C.5.-Utilisez-la-même-logique-pour-créer-un-vecteur-c4-contenant-les-valeurs-entre-8-et-12-et-entre-15-et-17-de-c1.-1.2.3.5">II.C.5. Utilisez la même logique pour créer un vecteur c4 contenant les valeurs entre 8 et 12 et entre 15 et 17 de c1.</a></span></li><li><span><a href="#II.C.6.-Trouvez-une-manière-de-remplacer-les-éléments-de-c1-respectant-la-condition-cond1-par-zéro." data-toc-modified-id="II.C.6.-Trouvez-une-manière-de-remplacer-les-éléments-de-c1-respectant-la-condition-cond1-par-zéro.-1.2.3.6">II.C.6. Trouvez une manière de remplacer les éléments de c1 respectant la condition cond1 par zéro.</a></span></li></ul></li><li><span><a href="#II.D.-Création-de-matrices" data-toc-modified-id="II.D.-Création-de-matrices-1.2.4">II.D. Création de matrices</a></span><ul class="toc-item"><li><span><a href="#II.D.1.-Lisez-la-documentation-de-la-fonction-matrix.-Utilisez-cette-fonction-pour-créer-une-matrice-mat1-de-cette-forme-:" data-toc-modified-id="II.D.1.-Lisez-la-documentation-de-la-fonction-matrix.-Utilisez-cette-fonction-pour-créer-une-matrice-mat1-de-cette-forme-:-1.2.4.1">II.D.1. Lisez la documentation de la fonction matrix. Utilisez cette fonction pour créer une matrice mat1 de cette forme :</a></span></li><li><span><a href="#II.D.2.-Toujours-avec-matrix,-essayez-de-créer-une-matrice-mat2-de-cette-forme" data-toc-modified-id="II.D.2.-Toujours-avec-matrix,-essayez-de-créer-une-matrice-mat2-de-cette-forme-1.2.4.2">II.D.2. Toujours avec matrix, essayez de créer une matrice mat2 de cette forme</a></span></li><li><span><a href="#II.D.3.-Que-sortent-mat1[1,-],-mat1[5,-],-mat1[,-2],-mat1[1,-4]?" data-toc-modified-id="II.D.3.-Que-sortent-mat1[1,-],-mat1[5,-],-mat1[,-2],-mat1[1,-4]?-1.2.4.3">II.D.3. Que sortent mat1[1, ], mat1[5, ], mat1[, 2], mat1[1, 4]?</a></span></li><li><span><a href="#II.D.4.--On-travaille-maintenant-avec-la-matrice-mat2-définie-ainsi-:" data-toc-modified-id="II.D.4.--On-travaille-maintenant-avec-la-matrice-mat2-définie-ainsi-:-1.2.4.4">II.D.4.  On travaille maintenant avec la matrice mat2 définie ainsi :</a></span></li><li><span><a href="#II.D.5.-Affichez-les-éléments-de-la-matrice-supérieurs-à-10." data-toc-modified-id="II.D.5.-Affichez-les-éléments-de-la-matrice-supérieurs-à-10.-1.2.4.5">II.D.5. Affichez les éléments de la matrice supérieurs à 10.</a></span></li><li><span><a href="#II.D.6.-Remplacez-les-éléments-de-la-matrice-supérieurs-à-10-par-zéro." data-toc-modified-id="II.D.6.-Remplacez-les-éléments-de-la-matrice-supérieurs-à-10-par-zéro.-1.2.4.6">II.D.6. Remplacez les éléments de la matrice supérieurs à 10 par zéro.</a></span></li><li><span><a href="#II.D.7.-Selon-vous,-que-va-donner-l’instruction-suivante-:" data-toc-modified-id="II.D.7.-Selon-vous,-que-va-donner-l’instruction-suivante-:-1.2.4.7">II.D.7. Selon vous, que va donner l’instruction suivante :</a></span></li><li><span><a href="#II.D.8.-Essayez-à-votre-tour-:-affichez-les-3e-et-4e-colonnes-de-la-matrice-mat4-lorsque-la-2nde-colonne-est-inférieure-à-50." data-toc-modified-id="II.D.8.-Essayez-à-votre-tour-:-affichez-les-3e-et-4e-colonnes-de-la-matrice-mat4-lorsque-la-2nde-colonne-est-inférieure-à-50.-1.2.4.8">II.D.8. Essayez à votre tour : affichez les 3e et 4e colonnes de la matrice mat4 lorsque la 2nde colonne est inférieure à 50.</a></span></li><li><span><a href="#II.D.9.-Utilisez-la-fonction-colnames()-pour-nommer-les-4-colonnes-de-mat4-comme-vous-le-souhaitez." data-toc-modified-id="II.D.9.-Utilisez-la-fonction-colnames()-pour-nommer-les-4-colonnes-de-mat4-comme-vous-le-souhaitez.-1.2.4.9">II.D.9. Utilisez la fonction colnames() pour nommer les 4 colonnes de mat4 comme vous le souhaitez.</a></span></li><li><span><a href="#II.D.10.-Sélectionnez-deux-colonnes-par-leurs-noms." data-toc-modified-id="II.D.10.-Sélectionnez-deux-colonnes-par-leurs-noms.-1.2.4.10">II.D.10. Sélectionnez deux colonnes par leurs noms.</a></span></li><li><span><a href="#II.D.11.-Essayez-d’utiliser-des-fonctions-de-statistiques-de-base-directement-sur-des-matrices-(somme,-moyenne,-min,-max).-Comment-s’appliquent-elles?" data-toc-modified-id="II.D.11.-Essayez-d’utiliser-des-fonctions-de-statistiques-de-base-directement-sur-des-matrices-(somme,-moyenne,-min,-max).-Comment-s’appliquent-elles?-1.2.4.11">II.D.11. Essayez d’utiliser des fonctions de statistiques de base directement sur des matrices (somme, moyenne, min, max). Comment s’appliquent-elles?</a></span></li></ul></li></ul></li><li><span><a href="#III.-Les-conditions-et-les-boucles" data-toc-modified-id="III.-Les-conditions-et-les-boucles-1.3">III. Les conditions et les boucles</a></span><ul class="toc-item"><li><span><a href="#III.A.-Les-boucles" data-toc-modified-id="III.A.-Les-boucles-1.3.1">III.A. Les boucles</a></span></li><li><span><a href="#III.B.-If…then…" data-toc-modified-id="III.B.-If…then…-1.3.2">III.B. If…then…</a></span><ul class="toc-item"><li><span><a href="#III.B.1.-À-vous!-En-faisant-tourner-une-boucle,-renvoyez-les-indices-des-lignes-de-mat4-dont-la-troisième-colonne-est-<-40." data-toc-modified-id="III.B.1.-À-vous!-En-faisant-tourner-une-boucle,-renvoyez-les-indices-des-lignes-de-mat4-dont-la-troisième-colonne-est-<-40.-1.3.2.1">III.B.1. À vous! En faisant tourner une boucle, renvoyez les indices des lignes de mat4 dont la troisième colonne est &lt; 40.</a></span></li><li><span><a href="#III.B.2.-Bonus-:-seriez-vous-capables-de-me-stocker-les-résultats-dans-un-vecteur,-comme-je-l’ai-fait-ici-:" data-toc-modified-id="III.B.2.-Bonus-:-seriez-vous-capables-de-me-stocker-les-résultats-dans-un-vecteur,-comme-je-l’ai-fait-ici-:-1.3.2.2">III.B.2. Bonus : seriez-vous capables de me stocker les résultats dans un vecteur, comme je l’ai fait ici :</a></span></li></ul></li></ul></li><li><span><a href="#IV.-Les-listes-et-les-fonctions" data-toc-modified-id="IV.-Les-listes-et-les-fonctions-1.4">IV. Les listes et les fonctions</a></span><ul class="toc-item"><li><span><a href="#IV.A.-Les-listes" data-toc-modified-id="IV.A.-Les-listes-1.4.1">IV.A. Les listes</a></span><ul class="toc-item"><li><span><a href="#IV.A.1.-À-vous!-créez-une-liste-contenant-une-matrice-numérique-que-vous-nommerez-mat_liste,-un-charactère-ch_liste-et-un-booléen-bool_liste.-Faites-la-somme-des-éléments-de-la-matrice-appelée-depuis-la-liste." data-toc-modified-id="IV.A.1.-À-vous!-créez-une-liste-contenant-une-matrice-numérique-que-vous-nommerez-mat_liste,-un-charactère-ch_liste-et-un-booléen-bool_liste.-Faites-la-somme-des-éléments-de-la-matrice-appelée-depuis-la-liste.-1.4.1.1">IV.A.1. À vous! créez une liste contenant une matrice numérique que vous nommerez mat_liste, un charactère ch_liste et un booléen bool_liste. Faites la somme des éléments de la matrice appelée depuis la liste.</a></span></li></ul></li><li><span><a href="#IV.B.-Les-fonctions" data-toc-modified-id="IV.B.-Les-fonctions-1.4.2">IV.B. Les fonctions</a></span><ul class="toc-item"><li><span><a href="#IV.B.1.-À-vous!-Créez-une-fonction-is_pair" data-toc-modified-id="IV.B.1.-À-vous!-Créez-une-fonction-is_pair-1.4.2.1">IV.B.1. À vous! Créez une fonction is_pair</a></span></li></ul></li></ul></li><li><span><a href="#VI.-Appliquer-des-fonctions-à-un-ensemble-d’éléments-avec-*apply" data-toc-modified-id="VI.-Appliquer-des-fonctions-à-un-ensemble-d’éléments-avec-*apply-1.5">VI. Appliquer des fonctions à un ensemble d’éléments avec *apply</a></span><ul class="toc-item"><li><span><a href="#VI.1-Exemple-:-Créez-une-matrice-numérique-mat5-de-dimension-20-*-3-avec-la-fonction-sample." data-toc-modified-id="VI.1-Exemple-:-Créez-une-matrice-numérique-mat5-de-dimension-20-*-3-avec-la-fonction-sample.-1.5.1">VI.1 Exemple : Créez une matrice numérique mat5 de dimension 20 * 3 avec la fonction sample.</a></span></li><li><span><a href="#VI.2.-Sortez-le-numéro-de-la-ligne-de-votre-matrice-correspondant-à-la-plus-faible-somme-des-colonnes." data-toc-modified-id="VI.2.-Sortez-le-numéro-de-la-ligne-de-votre-matrice-correspondant-à-la-plus-faible-somme-des-colonnes.-1.5.2">VI.2. Sortez le numéro de la ligne de votre matrice correspondant à la plus faible somme des colonnes.</a></span></li><li><span><a href="#VI.3.-En-utilisant-sum-et-is_pair,-sortez-le-numéro-de-la-ligne-contenant-le-plus-de-nombres-pairs." data-toc-modified-id="VI.3.-En-utilisant-sum-et-is_pair,-sortez-le-numéro-de-la-ligne-contenant-le-plus-de-nombres-pairs.-1.5.3">VI.3. En utilisant sum et is_pair, sortez le numéro de la ligne contenant le plus de nombres pairs.</a></span></li></ul></li><li><span><a href="#Pour-illustrer-tapply,-nous-allons-définir-la-matrice-mat6-ainsi-:" data-toc-modified-id="Pour-illustrer-tapply,-nous-allons-définir-la-matrice-mat6-ainsi-:-1.6">Pour illustrer tapply, nous allons définir la matrice mat6 ainsi :</a></span></li><li><span><a href="#VII.-Les-packages" data-toc-modified-id="VII.-Les-packages-1.7">VII. Les packages</a></span><ul class="toc-item"><li><span><a href="#VII.1.-Trouvez-comment-installer-un-package-sous-R-et-installez-le-package-readxl." data-toc-modified-id="VII.1.-Trouvez-comment-installer-un-package-sous-R-et-installez-le-package-readxl.-1.7.1">VII.1. Trouvez comment installer un package sous R et installez le package readxl.</a></span></li><li><span><a href="#VII.2.-Trouvez-comment-charger-le-package-dans-votre-session-pour-accéder-aux-fonctions.-Pouvez-vous-ne-charger-qu’une-des-fonctions-du-package?-Comment?" data-toc-modified-id="VII.2.-Trouvez-comment-charger-le-package-dans-votre-session-pour-accéder-aux-fonctions.-Pouvez-vous-ne-charger-qu’une-des-fonctions-du-package?-Comment?-1.7.2">VII.2. Trouvez comment charger le package dans votre session pour accéder aux fonctions. Pouvez-vous ne charger qu’une des fonctions du package? Comment?</a></span></li></ul></li></ul></li></ul></div>

## I. Prise en main du logiciel

On commence par installer R : http://cran.r-project.org/bin/windows/base/. 
Puis, on installe la version opensource de RStudio à partir de ce lien : http://www.rstudio.com/products/rstudio/download/

### I.A. Quelques astuces avant de commencer

Sur R, on assigne une valeur à un objet avec <-. Dans RStudio, vous pouvez le sortir directement avec le raccourci clavier Alt + 6.
Sur R, les lignes de commentaires commencent par #. Dans RStudio, vous pouvez passer ou dépasser rapidement une ou plusieurs lignes en commentaire avec le raccourci Ctrl + Maj + C.
Sur Rstudio, vous pouvez aussi organiser votre code en sections en faisant commencer votre section par # Mon titre de section ####. Essayez avec ces petits exercices!

### I.B. Premières manipulations

On crée les objets suivants dans une nouvelle session R :

In [1]:
a <- 3
b <- "ah tiens"
c <- TRUE

#### I.B.1. Faites tourner le code ci-dessus puis faites un appel à la fonction ls(). À quoi sert cette fonction?

In [2]:
ls()

[1] "a" "b" "c"

#### I.B.2. Appliquez la fonction mode() à chacun de ces objets. Décrivez les différents types d’objets obtenus.

In [3]:
mode(a)
mode(b)
mode(c)

[1] "numeric"

[1] "character"

[1] "logical"

#### I.B.3. Que font les fonctions is.numeric, is.logical et is.character? Testez-les sur ces objets.

In [6]:
is.numeric(a)
is.logical(b)
is.character(c)
is.numeric(b)
is.logical(c)
is.character(a)
is.numeric(c)
is.logical(a)
is.character(b)

[1] TRUE

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

#### I.B.4. Même question avec as.numeric, as.logical et as.character. Expliquez les résultats de as.numeric(c) et as.logical(a).

In [7]:
as.numeric(a)
as.logical(b)
as.character(c)
as.numeric(b)
as.logical(c)
as.character(a)
as.numeric(c)
as.logical(a)
as.character(b)

[1] 3

[1] NA

[1] "TRUE"

Warning message in eval(expr, envir, enclos):
"NAs introduits lors de la conversion automatique"

[1] NA

[1] TRUE

[1] "3"

[1] 1

[1] TRUE

[1] "ah tiens"

#### I.B.5. Trouvez une fonction permettant de supprimer des objets en mémoire. Utilisez-là pour supprimer a, puis pour supprimer b et c.

In [12]:
rm(a)

#### I.B.6. Aprés avoir créé de nouveau ces objets, trouvez une manière de supprimer l’ensemble des objets en mémoire (sans faire référence à leurs noms).

In [10]:
rm(ls)

Warning message in rm(ls):
"objet 'ls' introuvable"

### I.C. Documentation des fonctions

#### I.C.1. Trouvez une manière d’afficher l’aide de la fonction is.numeric. Essayez d’identifier les grandes parties de cette documentation.

In [8]:
?is.numeric

#### I.C.2. Lancez ??is.numeric. Qu’est-ce qu’on obtient?

In [9]:
??is.numeric

starting httpd help server ... done


! pb connu avec python 3.6 et RStudio pour cette commande

In [ ]:
help.search("is.numeric")
help.search("numeric")

#### I.C.3. Trouvez comment afficher le code d’une fonction R dans la console.

fct #sans les parenthèses

In [13]:
is.numeric

function (x)  .Primitive("is.numeric")

## II. Manipulations d’objets

### II.A. Création de vecteurs

#### II.A.1. Affichez la documentation de la fonction c(). 
Utilisez là pour créer un vecteur my_vec_num de 6 éléments numériques de votre choix.

In [23]:
?c()

In [14]:
my_vec_num <- c(1, 2, 3, 4, 5, 6)

In [4]:
my_vec_num

[1] 1 2 3 4 5 6

#### II.A.2. Trouvez une fonction permettant de vérifier que ce vecteur est bien numérique.

In [5]:
is.numeric(my_vec_num)

[1] TRUE

#### II.A.3. Trouvez une manière d’afficher la longueur de ce vecteur.

In [10]:
lenght(my_vec_num)

ERROR: Error in lenght(my_vec_num): impossible de trouver la fonction "lenght"


In [ ]:
length()

#### II.A.4. Faites tourner str(my_vec). Qu’obtient-on?

In [11]:
str(my_vec)

ERROR: Error in str(my_vec): objet 'my_vec' introuvable


#### II.A.5. Ajoutez deux valeurs numériques à votre vecteur sans le créer de nouveau.

In [12]:
my_vec_num <- c(7, 8)

In [15]:
my_vec_num

[1] 1 2 3 4 5 6

#### II.A.6. Refaire les étapes ci-dessus avec cette fois my_vec_logi composé d’éléments logiques et my_vec_charac composé d’éléments caractères.

In [20]:
my_vec_logi <- c(l1 = TRUE, l2 = FALSE)
my_vec_charac <- c("un", "deux", "trois")

#### II.A.7. Concaténez my_vec_num, my_vec_logi et my_vec_charac. Quel type de vecteur obtient-on?

In [21]:
c(my_vec_num, my_vec_logi, my_vec_charac)

l1      l2                 
    "1"     "2"     "3"     "4"     "5"     "6"  "TRUE" "FALSE"    "un"  "deux" 
        
"trois"

### II.B. Opérations de base sur les vecteurs

#### II.B.1. Trouvez une manière de créer un vecteur répliquant le même élément n fois.

In [17]:
rep(c(4),4)

[1] 4 4 4 4

#### II.B.2. Créez un vecteur c1 contenant les chiffres allant de 8 à 30 en utilisant deux méthodes différentes.

In [18]:
c1 <- 8 : 30

In [19]:
c1

[1]  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

In [20]:
seq.int(8, 30)

[1]  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

In [21]:
seq(from=8, to=30, by=2)

[1]  8 10 12 14 16 18 20 22 24 26 28 30

In [22]:
seq(8, 30, 2)

[1]  8 10 12 14 16 18 20 22 24 26 28 30

#### II.B.3. Trouvez une manière d’afficher le 1er élément de c1, puis le 15e. Vous notez une différence avec Python?

In [23]:
c1[1]

[1] 8

In [24]:
c1[15]

[1] 22

#### II.B.4. Créez un vecteur c2 contenant le 2nd, le 5e et le 8e élément de c1.

In [25]:
c2 <- c(c1[2], c1[5], c1[8])

In [26]:
c2

[1]  9 12 15

In [27]:
c2 <- c1[c(2,5,8)]

In [28]:
c2

[1]  9 12 15

#### II.B.5. Créez un vecteur c3 contenant tous les éléments de c2 sauf le 2e.

In [29]:
c3 <- c2[-2]

In [30]:
c3

[1]  9 15

#### II.B.6. Faites tourner names(c2) <- c("pommes","poires", "prunes") puis affichez c2 et str(c2). Que s’est-il passé? 

In [31]:
names(c2) <- c("pommes","poires", "prunes")

In [32]:
c2

pommes poires prunes 
     9     12     15

In [33]:
str(c2)

 Named int [1:3] 9 12 15
 - attr(*, "names")= chr [1:3] "pommes" "poires" "prunes"


Quelle autre possibilité s’offre à moi pour sélectionner des éléments de c2 dorénavant?

In [34]:
c2["poires"]

poires 
    12

#### II.B.7. Essayez d’utiliser des fonctions de statistiques de base directement sur des vecteurs (somme, moyenne, min, max). Comment s’appliquent-elles?

In [36]:
sum(1, 2, 3, 4, 5)

[1] 15

In [37]:
cx <- c(1, 2, 3, 4, 5)
mean(cx)

[1] 3

In [38]:
min(cx)

[1] 1

In [39]:
max(cx)

[1] 5

### II.C. Expressions logiques et conditions

#### II.C.1. Faites tourner c1 < 16. 
Expliquez la sortie obtenue. Utilisez la même logique pour sortir les vecteurs des conditions “c1 égal à 14” et “c1 différent de 9”.

In [40]:
c1 < 16

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [41]:
c1 == 14

[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [42]:
c1 != 9

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

#### II.C.2. Sortez le vecteur de condition “c1 est égal à 12 ou à 28”.

In [43]:
c1 == 12 | c1 == 28

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE

#### II.C.3. Créez le vecteur de condition cond1 “c1 est supérieur à 16 et inférieur à 22”.

filtre

In [44]:
cond1 <- c1 > 16 & c1 < 22

In [45]:
cond1

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

#### II.C.4. Faites tourner c1[cond1]. Qu’observez vous?

In [46]:
c1[cond1]

[1] 17 18 19 20 21

#### II.C.5. Utilisez la même logique pour créer un vecteur c4 contenant les valeurs entre 8 et 12 et entre 15 et 17 de c1.

In [47]:
cond2 <- c1 > 8 & c1 < 13 | c1 > 15 & c1 < 18

In [48]:
c4 <- c1[cond2]

In [49]:
c4

[1]  9 10 11 12 16 17

#### II.C.6. Trouvez une manière de remplacer les éléments de c1 respectant la condition cond1 par zéro.

In [78]:
c1 <- c1[cond1] <- 0

In [79]:
c1

[1] 0

### II.D. Création de matrices

#### II.D.1. Lisez la documentation de la fonction matrix. Utilisez cette fonction pour créer une matrice mat1 de cette forme :

In [56]:
##       [,1] [,2] [,3] [,4]
##  [1,]    1   11   21   31
##  [2,]    2   12   22   32
##  [3,]    3   13   23   33
##  [4,]    4   14   24   34
##  [5,]    5   15   25   35
##  [6,]    6   16   26   36
##  [7,]    7   17   27   37
##  [8,]    8   18   28   38
##  [9,]    9   19   29   39
## [10,]   10   20   30   40

In [57]:
rbind(1 ,2 ,3)

[,1]
[1,] 1   
[2,] 2   
[3,] 3

In [58]:
cbind(1, 2, 3)

[,1] [,2] [,3]
[1,] 1    2    3

In [59]:
rbind(c(1, 2, 3), c(4, 5, 6))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [60]:
cbind(c(1, 2, 3), c(4, 5, 6))

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [61]:
mat1 = matrix(data = 1:40, nrow = 10, ncol = 4)

In [62]:
mat1

[,1] [,2] [,3] [,4]
 [1,]  1   11   21   31  
 [2,]  2   12   22   32  
 [3,]  3   13   23   33  
 [4,]  4   14   24   34  
 [5,]  5   15   25   35  
 [6,]  6   16   26   36  
 [7,]  7   17   27   37  
 [8,]  8   18   28   38  
 [9,]  9   19   29   39  
[10,] 10   20   30   40

Affichez le type, le nombre de colonnes, le nombre de lignes et la longueur de cette matrice.

In [63]:
dim(mat1)

[1] 10  4

In [65]:
length(mat1)

[1] 40

#### II.D.2. Toujours avec matrix, essayez de créer une matrice mat2 de cette forme

In [66]:
##       [,1] [,2] [,3] [,4]
##  [1,]    1    2    3    4
##  [2,]    5    6    7    8
##  [3,]    9   10   11   12
##  [4,]   13   14   15   16
##  [5,]   17   18   19   20
##  [6,]   21   22   23   24
##  [7,]   25   26   27   28
##  [8,]   29   30   31   32
##  [9,]   33   34   35   36
## [10,]   37   38   39   40

In [67]:
mat2 <- matrix (1:40, 10, 4, byrow=TRUE)

In [68]:
mat2

[,1] [,2] [,3] [,4]
 [1,]  1    2    3    4  
 [2,]  5    6    7    8  
 [3,]  9   10   11   12  
 [4,] 13   14   15   16  
 [5,] 17   18   19   20  
 [6,] 21   22   23   24  
 [7,] 25   26   27   28  
 [8,] 29   30   31   32  
 [9,] 33   34   35   36  
[10,] 37   38   39   40

#### II.D.3. Que sortent mat1[1, ], mat1[5, ], mat1[, 2], mat1[1, 4]?

In [69]:
mat1[1, ]

[1]  1 11 21 31

premiere ligne

In [70]:
mat1[5, ]

[1]  5 15 25 35

In [71]:
mat1[, 2]

[1] 11 12 13 14 15 16 17 18 19 20

In [72]:
mat1[1, 4]

[1] 31

#### II.D.4.  On travaille maintenant avec la matrice mat2 définie ainsi :

In [87]:
mat4 <- matrix(sample(1:100, 40), nrow = 10, ncol = 4)
print(mat4)

      [,1] [,2] [,3] [,4]
 [1,]   51   83   15   43
 [2,]  100   52   79   25
 [3,]    4   72   26   46
 [4,]    6    1    5   60
 [5,]   64   34   90    7
 [6,]   49   95   42   82
 [7,]   98   62   29   73
 [8,]   18   97   39   92
 [9,]   27   16   94   76
[10,]   88   81   85   36


melange la liste

#### II.D.5. Affichez les éléments de la matrice supérieurs à 10.

In [74]:
cond10 <-mat4 > 10

In [75]:
mat4 <- mat4[cond10]

In [76]:
mat4

[1] 83 43 92 85 31 98 57 16 63 48 26 46 23 84 89 80 24 62 51 72 30 37 35 81 18
[26] 14 34 49 71 93 17 79 70 29 36 44

autre

In [77]:
mat4[mat4>10]

[1] 83 43 92 85 31 98 57 16 63 48 26 46 23 84 89 80 24 62 51 72 30 37 35 81 18
[26] 14 34 49 71 93 17 79 70 29 36 44

#### II.D.6. Remplacez les éléments de la matrice supérieurs à 10 par zéro.

Contrairement aux vecteurs, les matrices ont deux dimensions (lignes et colonnes). La logique de manipulation et de sélection reste cependant la même.

In [84]:
mat4[mat4>10] <- 0

In [85]:
mat4

[,1] [,2] [,3] [,4]
 [1,] 0    0    0    0   
 [2,] 0    0    0    0   
 [3,] 0    7    0    0   
 [4,] 0    0    0    0   
 [5,] 0    0    0    0   
 [6,] 0    0    0    0   
 [7,] 0    0    0    0   
 [8,] 9    0    0    0   
 [9,] 0    0    0    0   
[10,] 0    0    0    3

#### II.D.7. Selon vous, que va donner l’instruction suivante :

In [88]:
mat4[mat4[, 1] > 12, ]

[,1] [,2] [,3] [,4]
[1,]  51  83   15   43  
[2,] 100  52   79   25  
[3,]  64  34   90    7  
[4,]  49  95   42   82  
[5,]  98  62   29   73  
[6,]  18  97   39   92  
[7,]  27  16   94   76  
[8,]  88  81   85   36

#### II.D.8. Essayez à votre tour : affichez les 3e et 4e colonnes de la matrice mat4 lorsque la 2nde colonne est inférieure à 50.

In [89]:
mat4

[,1] [,2] [,3] [,4]
 [1,]  51  83   15   43  
 [2,] 100  52   79   25  
 [3,]   4  72   26   46  
 [4,]   6   1    5   60  
 [5,]  64  34   90    7  
 [6,]  49  95   42   82  
 [7,]  98  62   29   73  
 [8,]  18  97   39   92  
 [9,]  27  16   94   76  
[10,]  88  81   85   36

In [90]:
mat4[mat4[,2] < 50,]

[,1] [,2] [,3] [,4]
[1,]  6    1    5   60  
[2,] 64   34   90    7  
[3,] 27   16   94   76

afficher uniquemet les 3e et 4e colonnes

In [91]:
mat4[mat4[,2] < 50, c(3:4)]

[,1] [,2]
[1,]  5   60  
[2,] 90    7  
[3,] 94   76

#### II.D.9. Utilisez la fonction colnames() pour nommer les 4 colonnes de mat4 comme vous le souhaitez.

In [92]:
colnames(mat4) <- c("a","b","c","d")

In [93]:
mat4

a   b  c  d 
 [1,]  51 83 15 43
 [2,] 100 52 79 25
 [3,]   4 72 26 46
 [4,]   6  1  5 60
 [5,]  64 34 90  7
 [6,]  49 95 42 82
 [7,]  98 62 29 73
 [8,]  18 97 39 92
 [9,]  27 16 94 76
[10,]  88 81 85 36

#### II.D.10. Sélectionnez deux colonnes par leurs noms.

In [94]:
mat4[,c("a","b")]

a   b 
 [1,]  51 83
 [2,] 100 52
 [3,]   4 72
 [4,]   6  1
 [5,]  64 34
 [6,]  49 95
 [7,]  98 62
 [8,]  18 97
 [9,]  27 16
[10,]  88 81

#### II.D.11. Essayez d’utiliser des fonctions de statistiques de base directement sur des matrices (somme, moyenne, min, max). Comment s’appliquent-elles?

In [96]:
#somme
sum(mat4)

[1] 2142

In [97]:
#moyenne
mean(mat4)

[1] 53.55

In [98]:
#min
min(mat4)

[1] 1

In [99]:
max(mat4)

[1] 100

## III. Les conditions et les boucles

### III.A. Les boucles

Les boucles ont la même logique sur Python et sur R, mais la syntaxe diffère légèrement :

In [100]:
for (i in c(1:10)){ 
  # ! N'oubliez pas de mettre la condition entre parenthèses après le for et 
  # de définir la boucle à l'intérieur d'accolades
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


### III.B. If…then…

Les conditions if et then ont également la même logique sur Python et sur R, la syntaxe est la suivante :

In [101]:
for (i in c(1:10)){ 
  # ! N'oubliez pas de mettre la condition entre parenthèses après le for et 
  # de définir la boucle à l'intérieur d'accolades
  if (i <= 5){
    print(i)
  } else if (i == 6) {
    print(i * 100)
  } else {
    print(0)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 600
[1] 0
[1] 0
[1] 0
[1] 0


Note : Les accolades ne servent que pour écrire les conditions sur plusieurs lignes, on peut de manière équivalente écrire :

In [102]:
for (i in c(1:10)){ 
  # ! N'oubliez pas de mettre la condition entre parenthèses après le for et 
  # de définir la boucle à l'intérieur d'accolades
  if (i <= 5) print(i) 
  else  if (i == 6) print(i * 100)
  else print(0)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 600
[1] 0
[1] 0
[1] 0
[1] 0


#### III.B.1. À vous! En faisant tourner une boucle, renvoyez les indices des lignes de mat4 dont la troisième colonne est < 40.

In [104]:
mat4

a   b  c  d 
 [1,]  51 83 15 43
 [2,] 100 52 79 25
 [3,]   4 72 26 46
 [4,]   6  1  5 60
 [5,]  64 34 90  7
 [6,]  49 95 42 82
 [7,]  98 62 29 73
 [8,]  18 97 39 92
 [9,]  27 16 94 76
[10,]  88 81 85 36

In [105]:
mat4[,c("c")]

[1] 15 79 26  5 90 42 29 39 94 85

In [111]:
for (i in mat4[,c("c")]){
    if (i < 40) print(i)
}

[1] 15
[1] 26
[1] 5
[1] 29
[1] 39


In [142]:
row = 0
for (i in mat4[,c("c")]){ 
    row = row + 1
    if (i < 40){
        r = as.character(row)
        i = as.character(i)
        #print(i, r)
        str = paste(i, r, sep=" ")
        print(str)
    }
}

[1] "15 1"
[1] "26 3"
[1] "5 4"
[1] "29 7"
[1] "39 8"


#### III.B.2. Bonus : seriez-vous capables de me stocker les résultats dans un vecteur, comme je l’ai fait ici :

In [107]:
## [1] 4 5 6 8

In [143]:
vec = c(r)

In [144]:
vec

[1] "8"

## IV. Les listes et les fonctions

### IV.A. Les listes

Les listes sont des ensembles d’éléments pas forcément de même type. Une liste se définit avec la fonction list :

In [145]:
l1 <- list(1, "ah tiens", 4, " qu'est-ce que je fais à côté d'un 4")
l1

[[1]]
[1] 1

[[2]]
[1] "ah tiens"

[[3]]
[1] 4

[[4]]
[1] " qu'est-ce que je fais à côté d'un 4"

Les éléments peuvent s’appeler avec leur position ou, lorsqu’ils en ont, de leur nom :

In [152]:
l2 <- list("var1" = 1, "var2" = "v'là autre chose", "var3" = 4, "var4" = "je ne suis pas un numéro")
l2[["var3"]]

[1] 4

In [153]:
l2[[3]]

[1] 4

Attention : [ renvoie à la sous-liste de l’élément demandé, ici le numéro 4 et le nom associé :

In [154]:
l2["var3"]

$var3
[1] 4

Au contraire, [[ renvoie directement à l’élément, soit 4. Cette dernière notation est équivalent à l’appel avec $, lorsque la liste est nommée, que nous utiliserons le plus souvent pour faire appel à une variable d’un dataframe :

In [155]:
l2$var3

[1] 4

Enfin, on peut concaténer des listes entre elles avec c() :

In [156]:
l3 <- c(l1, l2)
print(l3)

[[1]]
[1] 1

[[2]]
[1] "ah tiens"

[[3]]
[1] 4

[[4]]
[1] " qu'est-ce que je fais à côté d'un 4"

$var1
[1] 1

$var2
[1] "v'là autre chose"

$var3
[1] 4

$var4
[1] "je ne suis pas un numéro"



#### IV.A.1. À vous! créez une liste contenant une matrice numérique que vous nommerez mat_liste, un charactère ch_liste et un booléen bool_liste. Faites la somme des éléments de la matrice appelée depuis la liste.

In [158]:
# une matrice numérique
mat_liste = matrix(data = 1:4, nrow = 2, ncol = 2)
mat_liste

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [159]:
ch_liste = "v'là autre chose"
ch_liste

[1] "v'là autre chose"

In [160]:
bool_liste = TRUE

In [161]:
l4 <- c(mat_liste , ch_liste, bool_liste)

In [162]:
l4

[1] "1"                "2"                "3"                "4"               
[5] "v'là autre chose" "TRUE"

In [179]:
sum(which(l4==as.integer(l4)))

Warning message in which(l4 == as.integer(l4)):
"NAs introduits lors de la conversion automatique"

[1] 10

### IV.B. Les fonctions

Les fonctions dans R se définissent ainsi :

In [136]:
ma_fonc <- function(x1, x2){
  x3 <- x1 + x2
  return(x3)
}
ma_fonc(4, 6)

[1] 10

On peut définir des valeurs par défaut :

In [137]:
ma_fonc <- function(x1 = 2, x2 = 4){
  x3 <- x1 + x2
  return(x3)
}
ma_fonc()

[1] 6

In [138]:
ma_fonc(4, 6)

[1] 10

Enfin, on peut définir des sorties multiples :

In [139]:
ma_fonc <- function(x1 = 2, x2 = 4){
  x3 <- x1 + x2
  x4 <- x1 * x2
  return(list(x3, x4))
}
ma_fonc(4, 6)

[[1]]
[1] 10

[[2]]
[1] 24

#### IV.B.1. À vous! Créez une fonction is_pair
qui renvoie TRUE si le paramètre en entrée est pair, FALSE sinon. 
Faites en sorte qu’une erreur s’affiche si le paramètre en entrée n’est pas une variable numérique
(utilisez pour cela la fonction stop())

On a les mêmes résultats ? :

In [182]:
is_pair <- function(x){
    if (x==is.character(x)) stop()
    else if (x%%2 == 0) return(TRUE)
    else return(FALSE)
}

In [183]:
is_pair(2)

[1] TRUE

In [184]:
is_pair(5)

[1] FALSE

In [185]:
is_pair(3895874)

[1] TRUE

In [186]:
is_pair("mais enfin")

ERROR: Error in x%%2: argument non numérique pour un opérateur binaire


## VI. Appliquer des fonctions à un ensemble d’éléments avec *apply

La fonction apply permet d’appliquer une fonction à une certaine dimension d’une matrice. 
Elle s’écrit apply(X, MARGIN, FUN, ...) avec 
* X la matrice (ou le dataframe) considéré, 
* MARGIN le numéro correspondant à la marge (1 si on applique sur les lignes, 2 sur les colonnes).

### VI.1 Exemple : Créez une matrice numérique mat5 de dimension 20 * 3 avec la fonction sample. 
Lancez sum(mat5), apply(mat5, 1, sum) et apply(mat5, 2, sum). Expliquez les résultats.

In [188]:
mat5 <- matrix(sample(1:100, 60), nrow = 20, ncol = 3)
print(mat5)

      [,1] [,2] [,3]
 [1,]   78    4   86
 [2,]   85   45   29
 [3,]   46   26   40
 [4,]   20   97    8
 [5,]   69   32   76
 [6,]   37    2   62
 [7,]   74   28   56
 [8,]   91   38   51
 [9,]   70   82   11
[10,]    7   35   66
[11,]   75   17   22
[12,]   83   81   77
[13,]   64   27   92
[14,]   18   63   33
[15,]   23   94   87
[16,]   55   39   19
[17,]   36   60   47
[18,]   30    3  100
[19,]   43   73   50
[20,]   48   93   79


In [189]:
sum(mat5)

[1] 3082

In [190]:
apply(mat5, 1, sum)

[1] 168 159 112 125 177 101 158 180 163 108 114 241 183 114 204 113 143 133 166
[20] 220

In [191]:
apply(mat5, 2, sum)

[1] 1052  939 1091

### VI.2. Sortez le numéro de la ligne de votre matrice correspondant à la plus faible somme des colonnes.
!!! ? erreur lignes ?

In [192]:
min(apply(mat5, 1, sum))

[1] 101

In [208]:
row = 0
sumrows = apply(mat5, 1, sum)
for (i in sumrows){
    row = row +1
    #print(i)
    if (i == min(sumrows)){
            print(row)
        }
    }

[1] 6


### VI.3. En utilisant sum et is_pair, sortez le numéro de la ligne contenant le plus de nombres pairs.

Question étrange : il y a plusieurs ligne qui ont toutes les valeurs pairs

In [212]:
pair = lapply(mat5, is_pair)

In [215]:
pair

[[1]]
[1] TRUE

[[2]]
[1] FALSE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

[[5]]
[1] FALSE

[[6]]
[1] FALSE

[[7]]
[1] TRUE

[[8]]
[1] FALSE

[[9]]
[1] TRUE

[[10]]
[1] FALSE

[[11]]
[1] FALSE

[[12]]
[1] FALSE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

[[15]]
[1] FALSE

[[16]]
[1] FALSE

[[17]]
[1] TRUE

[[18]]
[1] TRUE

[[19]]
[1] FALSE

[[20]]
[1] TRUE

[[21]]
[1] TRUE

[[22]]
[1] FALSE

[[23]]
[1] TRUE

[[24]]
[1] FALSE

[[25]]
[1] TRUE

[[26]]
[1] TRUE

[[27]]
[1] TRUE

[[28]]
[1] TRUE

[[29]]
[1] TRUE

[[30]]
[1] FALSE

[[31]]
[1] FALSE

[[32]]
[1] FALSE

[[33]]
[1] FALSE

[[34]]
[1] FALSE

[[35]]
[1] TRUE

[[36]]
[1] FALSE

[[37]]
[1] TRUE

[[38]]
[1] FALSE

[[39]]
[1] FALSE

[[40]]
[1] FALSE

[[41]]
[1] TRUE

[[42]]
[1] FALSE

[[43]]
[1] TRUE

[[44]]
[1] TRUE

[[45]]
[1] TRUE

[[46]]
[1] TRUE

[[47]]
[1] TRUE

[[48]]
[1] FALSE

[[49]]
[1] FALSE

[[50]]
[1] TRUE

[[51]]
[1] TRUE

[[52]]
[1] FALSE

[[53]]
[1] TRUE

[[54]]
[1] FALSE

[[55]]
[1] FALSE

[[56]]
[1] FALSE

[[57]]
[1] FALSE

[[58]]
[1] TRUE

[[59]]
[1] TRUE

[[60]]
[1] FALSE

In [214]:
mat5[pair]

ERROR: Error in mat5[pair]: type 'list' d'indice incorrect


In [213]:
sumpair = apply(mat5[pair], 1, sum)

ERROR: Error in mat5[pair]: type 'list' d'indice incorrect


## Pour illustrer tapply, nous allons définir la matrice mat6 ainsi :

In [148]:
mat6 <- matrix(c(rep(1,5), rep(2,5), rep(3,5), rep(4, 5), sample(1:100, 60)), nrow = 20)
mat6


[,1] [,2] [,3] [,4]
 [1,] 1    71    41  24  
 [2,] 1    47    20  94  
 [3,] 1    18    10   6  
 [4,] 1    50    69  29  
 [5,] 1    15     9  56  
 [6,] 2    75   100   1  
 [7,] 2    81    48  57  
 [8,] 2    22    76  19  
 [9,] 2    80    84  34  
[10,] 2    90    61  93  
[11,] 3    77    38   8  
[12,] 3    79    25  85  
[13,] 3    26    83  87  
[14,] 3     4    44  67  
[15,] 3    42    58  43  
[16,] 4    52    14  37  
[17,] 4    88    49  68  
[18,] 4    63    70  74  
[19,] 4     2    96  66  
[20,] 4    32    99  51

In [149]:
tapply(mat6[, 2], mat6[, 1], sum)

1   2   3   4 
201 348 228 237

tapply(X, INDEX, FUN) va appliquer la fonction définie à un vecteur X pour chaque unique valeur d’un autre vecteur INDEX de la même taille. On peut par exemple obtenir le max de la colonne 2 pour chaque unique valeur de la colonne 1 :

In [150]:
tapply(mat6[, 2], mat6[, 1], max)

1  2  3  4 
71 90 79 88

Enfin, la fonction lapply permet d’appliquer une fonction à l’ensemble des éléments d’une liste. Si on prend par exemple la liste suivante :

In [151]:
l4 <- list("mat" = matrix(c(1:100), nrow = 50), "vec" = c(1,5,8,9), "num" = 2, "ch" = "Voilà")
l4

$mat
      [,1] [,2]
 [1,]    1   51
 [2,]    2   52
 [3,]    3   53
 [4,]    4   54
 [5,]    5   55
 [6,]    6   56
 [7,]    7   57
 [8,]    8   58
 [9,]    9   59
[10,]   10   60
[11,]   11   61
[12,]   12   62
[13,]   13   63
[14,]   14   64
[15,]   15   65
[16,]   16   66
[17,]   17   67
[18,]   18   68
[19,]   19   69
[20,]   20   70
[21,]   21   71
[22,]   22   72
[23,]   23   73
[24,]   24   74
[25,]   25   75
[26,]   26   76
[27,]   27   77
[28,]   28   78
[29,]   29   79
[30,]   30   80
[31,]   31   81
[32,]   32   82
[33,]   33   83
[34,]   34   84
[35,]   35   85
[36,]   36   86
[37,]   37   87
[38,]   38   88
[39,]   39   89
[40,]   40   90
[41,]   41   91
[42,]   42   92
[43,]   43   93
[44,]   44   94
[45,]   45   95
[46,]   46   96
[47,]   47   97
[48,]   48   98
[49,]   49   99
[50,]   50  100

$vec
[1] 1 5 8 9

$num
[1] 2

$ch
[1] "Voilà"

On peut par exemple sortir directement le type de chaque objet de la liste :

In [153]:
lapply(l4, class)

$mat
[1] "matrix"

$vec
[1] "numeric"

$num
[1] "numeric"

$ch
[1] "character"

Les familles de fonctions *apply sont optimisées sous R et souvent bien plus rapides que les boucles :

In [163]:
microbenchmark::microbenchmark(
  times = 100L,
  "Lapply" = results_ <- lapply(l4, class),
  "boucle" = {
    results <- list()
    for (i in c(1:length(l4))){
      results <- c(results, class(l4[i]))
    }
  })

expr   time   
1   boucle 2753500
2   boucle 2365900
3   boucle 2344500
4   boucle 2372400
5   boucle 2952500
6   Lapply    9500
7   Lapply    4200
8   Lapply    2900
9   Lapply    3000
10  boucle 2379300
11  boucle 2332000
12  boucle 2402000
13  boucle 2331800
14  Lapply    8100
15  boucle 2329400
16  boucle 2392200
17  boucle 2416400
18  Lapply    9000
19  Lapply    4100
20  Lapply    3300
21  Lapply    3000
22  boucle 2329600
23  Lapply    6900
24  boucle 2365100
25  boucle 2369900
26  boucle 2290400
27  Lapply    7400
28  boucle 2299700
29  boucle 2412300
30  boucle 2287300
... ...    ...    
171 Lapply    3400
172 boucle 2378000
173 boucle 2385200
174 boucle 2443600
175 Lapply    8600
176 boucle 2360100
177 boucle 2337700
178 boucle 2407000
179 boucle 2307400
180 boucle 2269400
181 Lapply    8200
182 Lapply    3500
183 Lapply    3300
184 Lapply    2800
185 Lapply    2900
186 boucle 2271200
187 boucle 2361400
188 boucle 2361600
189 Lapply    7400
190 Lapply    3800
191 Lapply    3500
192 boucle 2290600
193 boucle 2436200
194 boucle 2367100
195 Lapply    7700
196 Lapply    4700
197 boucle 4119700
198 Lapply    8800
199 boucle 2313800
200 boucle 2325100

## VII. Les packages

### VII.1. Trouvez comment installer un package sous R et installez le package readxl.

installé via anaconda

### VII.2. Trouvez comment charger le package dans votre session pour accéder aux fonctions. Pouvez-vous ne charger qu’une des fonctions du package? Comment?

In [ ]:
# Chargement du package "readxl"
library(readxl)